In [ ]:
import pandas as pd

In [ ]:
# Read TSV file into DataFrame

column = ["qid", "Q0", "docno", "rank", "score", "tag"]
df1 = pd.read_table('LKAU23_run60_ArabicBERT.tsv', names=column)



df2 = pd.read_table('LKAU23_run60_CL_AraBERT.tsv', names=column)

In [ ]:
df1

In [ ]:
df2

In [ ]:
# Extract the first 10

qid2=[]
Q02=[]
docno2=[]
score2=[]
tag2=[]
rank2=[]

flage=df1["qid"][0]
num=1
listate=[]
for index, row in df1.iterrows():
  if flage != row["qid"]:
    num=1
    flage = row["qid"]
    qid2.append(row["qid"])
    Q02.append(row["Q0"])
    docno2.append(row["docno"])
    score2.append(row["score"])
    tag2.append(row["tag"])
    rank2.append(num)
  else:
    if num <= 10:
      qid2.append(row["qid"])
      Q02.append(row["Q0"])
      docno2.append(row["docno"])
      score2.append(row["score"])
      tag2.append(row["tag"])
      rank2.append(num)

  num=num+1

dataa2 = {"qid":qid2, "Q0":Q02, "docno":docno2, "rank":rank2, "score":score2, "tag":tag2}


df1_final = pd.DataFrame(dataa2)
df1_final

     qid  Q0      docno  rank     score                      tag
0    500  Q0  37:99-113     1  0.632314  LKAU23_run60_ArabicBERT
1    500  Q0   14:35-41     2  0.595968  LKAU23_run60_ArabicBERT
2    500  Q0   19:41-50     3  0.573569  LKAU23_run60_ArabicBERT
3    500  Q0   21:69-73     4  0.555252  LKAU23_run60_ArabicBERT
4    500  Q0   11:69-76     5  0.546885  LKAU23_run60_ArabicBERT
..   ...  ..        ...   ...       ...                      ...
515  613  Q0  3:159-160     6  0.396859  LKAU23_run60_ArabicBERT
516  613  Q0   19:59-65     7  0.394501  LKAU23_run60_ArabicBERT
517  613  Q0    3:28-30     8  0.390165  LKAU23_run60_ArabicBERT
518  613  Q0   33:42-48     9  0.389617  LKAU23_run60_ArabicBERT
519  613  Q0   41:30-32    10  0.388753  LKAU23_run60_ArabicBERT

[520 rows x 6 columns]

In [ ]:
df1_final['tag'] = 'LKAU23_run62_ArabicBERT'

In [ ]:
df1_final

     qid  Q0      docno  rank     score                      tag
0    500  Q0  37:99-113     1  0.632314  LKAU23_run62_ArabicBERT
1    500  Q0   14:35-41     2  0.595968  LKAU23_run62_ArabicBERT
2    500  Q0   19:41-50     3  0.573569  LKAU23_run62_ArabicBERT
3    500  Q0   21:69-73     4  0.555252  LKAU23_run62_ArabicBERT
4    500  Q0   11:69-76     5  0.546885  LKAU23_run62_ArabicBERT
..   ...  ..        ...   ...       ...                      ...
515  613  Q0  3:159-160     6  0.396859  LKAU23_run62_ArabicBERT
516  613  Q0   19:59-65     7  0.394501  LKAU23_run62_ArabicBERT
517  613  Q0    3:28-30     8  0.390165  LKAU23_run62_ArabicBERT
518  613  Q0   33:42-48     9  0.389617  LKAU23_run62_ArabicBERT
519  613  Q0   41:30-32    10  0.388753  LKAU23_run62_ArabicBERT

[520 rows x 6 columns]

In [ ]:
df1_final.to_csv("LKAU23_run62.tsv", sep='\t', index=False, header=False)

In [ ]:
! python ../quran-qa-2023-main/Task-A/code/QQA23_TaskA_submission_checker.py \
    -m "LKAU23_run62.tsv"

Format check: Passed

In [ ]:
# Extract the first 10

qid2=[]
Q02=[]
docno2=[]
score2=[]
tag2=[]
rank2=[]

flage=df2["qid"][0]
num=1
listate=[]
for index, row in df2.iterrows():
  if flage != row["qid"]:
    num=1
    flage = row["qid"]
    qid2.append(row["qid"])
    Q02.append(row["Q0"])
    docno2.append(row["docno"])
    score2.append(row["score"])
    tag2.append(row["tag"])
    rank2.append(num)
  else:
    if num <= 10:
      qid2.append(row["qid"])
      Q02.append(row["Q0"])
      docno2.append(row["docno"])
      score2.append(row["score"])
      tag2.append(row["tag"])
      rank2.append(num)

  num=num+1

dataa2 = {"qid":qid2, "Q0":Q02, "docno":docno2, "rank":rank2, "score":score2, "tag":tag2}


df2_final = pd.DataFrame(dataa2)
df2_final

In [ ]:
df2_final['tag'] = "LKAU23_run63_CL_AraBERT"
df2_final

In [ ]:
df2_final.to_csv("LKAU23_run63.tsv", sep='\t', index=False, header=False)

In [ ]:
! python ../quran-qa-2023-main/Task-A/code/QQA23_TaskA_submission_checker.py \
    -m "LKAU23_run63.tsv"

Format check: Passed